# -*- coding: utf-8 -*-
"""lab_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UYJWnyiTrKWIBcWMANsqp7wTRzDZHorz

Activity 1
"""

n = input("Enter a number")
n = int(n)
if (n%2==0):
    print("it is even number")
else:
        print("not even")

"""Activity 2"""

sum = 0
n = int(input("Enter a number"))
while n!=0:
  sum = sum+n
  n = int(input("Enter a number"))
print("sum of all given values is ",sum)

"""Activity 3"""

isPrime = True
i = 2
n = int(input("Enter a number"))
while i<n:
  remainder = n%i
  if remainder == 0:
    isPrime = False
    break
  else:
    i = i+1
if isPrime:
  print("Number is prime")
else :
  print("Number is not prime")

"""Activity 4

"""

summ = 0
i = 0
while i <= 4:
  s = input("Enter a number")
  n = int(s)
  summ = summ+n
  i = i+1
print("sum is :",summ)

"""Activity 5"""

sum = 0
i = 1
while i < 11:
  sum = sum+i
  i=i+1
print("The sum of all values is ",sum)

"""Activity 7"""

import random

MINIMUM = 1
MAXIMUM = 9
NUMBER = random.randint(MINIMUM, MAXIMUM)
GUESS = None
ANOTHER = None
TRY = 0
RUNNING = True
print("Alright...")

while RUNNING:
    GUESS = input("What is your lucky number? ")

    # Check if user wants to exit
    if GUESS.lower() == "exit":
        print("Better luck next time.")
        break

    try:
        GUESS = int(GUESS)

        if GUESS < NUMBER:
            print("Wrong, too low.")
        elif GUESS > NUMBER:
            print("Wrong, too high.")
        elif GUESS == NUMBER:
            print(f"Yes, that's the one, {NUMBER}.")
            if TRY < 2:
                print(f"Impressive, only {TRY} tries.")
            elif 2 <= TRY < 10:
                print(f"Pretty good, {TRY} tries.")
            else:
                print(f"Bad, {TRY} tries.")
            RUNNING = False

        TRY += 1

    except ValueError:
        print("Please enter a valid number.")

"""Graded Lab Activity 1"""

number = int(input())
reversed_number = 0

while number > 0:
    reversed_number = reversed_number * 10 + number % 10
    number = number // 10

print(reversed_number)

"""Graded Lab Activity 2"""

numbers = input().split()
even_sum = 0
odd_sum = 0

for num in numbers:
    num = int(num)
    if num % 2 == 0:
        even_sum += num
    else:
        odd_sum += num

print("Even sum:", even_sum)
print("Odd sum:", odd_sum)

"""Graded Lab Activity 3"""

# With loop
n = int(input())
a, b = 0, 1
for _ in range(n):
    print(a, end=" ")
    a, b = b, a + b

# With recursion
def fibonacci(n, a=0, b=1):
    if n > 0:
        print(a, end=" ")
        fibonacci(n-1, b, a+b)

n = int(input())
fibonacci(n)

"""Graded Lab Activity 4"""

marks = int(input())
if marks < 50:
    print("Grade F")
elif marks <= 60:
    print("Grade E")
elif marks <= 70:
    print("Grade D")
elif marks <= 80:
    print("Grade C")
elif marks <= 90:
    print("Grade B")
else:
    print("Grade A")

"""Graded Lab Activity 5"""

n = int(input())
factorial = 1
for i in range(1, n+1):
    factorial *= i
print(factorial)